const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
let current='home', selectedEvent='creation', scale=1, pan={x:0,y:0}, dragging=false, start={x:0,y:0};
function setHead(t,s){$('#headTitle').textContent=t;$('#headSub').textContent=s||'성경연대기 독립 PWA';}
function go(page){current=page;$$('.page').forEach(p=>p.classList.remove('active'));$('#'+page).classList.add('active');$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.page===page));if(page==='home')setHead('성경연대기','창조와 원역사 · 족장 시대 · 출애굽과 광야');if(page==='timeline')setHead('시대별 연대기','사건칩을 눌러 상세 보기');if(page==='detail')setHead('핵심사건 상세','요약·의미·원본 인포그래픽');scrollTo(0,0);history.pushState({page},'',location.pathname+'#'+page)}
function renderHome(){ $('#eraCount').textContent=ERAS.length; $('#eventCount').textContent=ERAS.reduce((a,e)=>a+e.events.length,0); $('#eraMenu').innerHTML=ERAS.map(e=>`<button class="eraBtn" data-era="${e.id}"><b>${e.title}</b><span>${e.period}</span><em>${e.events.length}개 사건</em></button>`).join('');}
function renderTimeline(filter=''){const q=filter.trim().toLowerCase();$('#timelineRoot').innerHTML=ERAS.map(era=>{const ids=era.events.filter(id=>!q||EVENTS[id].title.toLowerCase().includes(q)||era.title.toLowerCase().includes(q)||EVENTS[id].summary.toLowerCase().includes(q)); if(!ids.length)return ''; return `<article class="eraCard" id="era-${era.id}"><div class="eraTop"><h2>${era.title}</h2><span>${era.period}</span></div><p>${era.summary}</p><div class="eventGrid">${ids.map(id=>`<button class="eventChip" data-event="${id}">${EVENTS[id].title}</button>`).join('')}</div></article>`}).join('')||'<div class="empty">검색 결과가 없습니다.</div>';}
function renderDetail(id){selectedEvent=id;const e=EVENTS[id];$('#detailRoot').innerHTML=`<section class="detailHero"><div class="eyebrow">${e.era}</div><h1>${e.title}</h1><div class="meta"><span>${e.period}</span><span>${e.scripture}</span></div></section>${section('1. 사건요약',`<p>${e.summary}</p>`)}${section('2. 핵심의미',list(e.meaning))}${section('3. 시대 / 연대',`<div class="bigline">${e.period}</div><p>${e.era}</p><p>${e.scripture}</p>`)}${section('4. 장소',`<p>${e.place}</p>`)}${section('5. 핵심인물',`<div class="tags">${e.people.map(x=>`<span>${x}</span>`).join('')}</div>`)}${section('6. 핵심사건',flow(e.core))}${section('7. 관련성경',`<p>${e.scripture}</p>`)}${section('8. 연결탐험',`<div class="connect">${e.connect.map(x=>`<span>${x}</span>`).join('')}</div>`)}${section('9. 원본 인포그래픽',`<button class="originalBtn" data-open="${id}">원본 인포그래픽 보기</button>`)} `;go('detail')}
function section(t,b){return `<section class="dcard"><h2>${t}</h2>${b}</section>`}function list(a){return `<ul>${a.map(x=>`<li>${x}</li>`).join('')}</ul>`}function flow(a){return `<div class="flow">${a.map((x,i)=>`<div><b>${i+1}</b><span>${x}</span></div>`).join('')}</div>`}
function openViewer(id){const e=EVENTS[id];scale=1;pan={x:0,y:0};$('#viewerTitle').textContent=e.title+' 원본 인포그래픽';$('#viewerImg').src=e.image;applyImg();$('#viewer').classList.add('show');$('#viewer').setAttribute('aria-hidden','false')}
function closeViewer(){$('#viewer').classList.remove('show');$('#viewer').setAttribute('aria-hidden','true');$('#viewerImg').src=''}function applyImg(){$('#viewerImg').style.transform=`translate(${pan.x}px,${pan.y}px) scale(${scale})`}
function init(){renderHome();renderTimeline();document.body.addEventListener('click',ev=>{const era=ev.target.closest('[data-era]');if(era){go('timeline');setTimeout(()=>$('#era-'+era.dataset.era)?.scrollIntoView({behavior:'smooth'}),50)}const nav=ev.target.closest('.nav');if(nav){if(nav.dataset.page)go(nav.dataset.page);if(nav.dataset.event)renderDetail(nav.dataset.event)}const chip=ev.target.closest('[data-event]');if(chip)renderDetail(chip.dataset.event);const open=ev.target.closest('[data-open]');if(open)openViewer(open.dataset.open);});$('#searchInput').addEventListener('input',e=>renderTimeline(e.target.value));$('#homeBtn').onclick=()=>go('home');$('#backBtn').onclick=()=>{if($('#viewer').classList.contains('show'))closeViewer();else if(current==='detail')go('timeline');else if(current==='timeline')go('home');else history.back();};$('#viewerClose').onclick=closeViewer;$('#zoomIn').onclick=()=>{scale=Math.min(4,scale+.25);applyImg()};$('#zoomOut').onclick=()=>{scale=Math.max(.5,scale-.25);applyImg()};const body=$('#viewerBody');body.addEventListener('pointerdown',e=>{dragging=true;start={x:e.clientX-pan.x,y:e.clientY-pan.y};body.setPointerCapture(e.pointerId)});body.addEventListener('pointermove',e=>{if(!dragging)return;pan={x:e.clientX-start.x,y:e.clientY-start.y};applyImg()});body.addEventListener('pointerup',()=>dragging=false);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});}document.addEventListener('DOMContentLoaded',init);
