const ERAS = [
  {id:'origin', title:'창조와 원역사', period:'BC 4000경 ~ BC 2200경', scripture:'창세기 1~11장', summary:'창조, 타락, 죄의 확산, 심판과 흩어짐을 보여주는 성경 역사의 출발점입니다.', events:['creation','adam-eve','eden-exile','cain-abel','noah-ark','babel-tower']},
  {id:'patriarch', title:'족장 시대', period:'BC 2000경 ~ BC 1800경', scripture:'창세기 12~50장', summary:'아브라함에게 주신 언약이 이삭, 야곱, 요셉으로 이어지며 언약 백성의 뿌리가 세워진 시대입니다.', events:['abraham-call','lot-sodom','jacob-ladder','jabbok-wrestling','joseph-dream','joseph-governor']},
  {id:'exodus', title:'출애굽과 광야 시대', period:'BC 1446경 ~ BC 1406경', scripture:'출애굽기 ~ 신명기', summary:'이스라엘이 애굽에서 해방되어 언약 백성으로 세워지고 광야에서 훈련받은 시대입니다.', events:['moses-birth','burning-bush','ten-plagues','passover','red-sea','manna-quail','sinai-commandments','golden-calf','tabernacle','wilderness-40','bronze-serpent']}
];

const EVENTS = {
'creation':{title:'창조', era:'창조와 원역사', period:'태초', scripture:'창세기 1~2장', place:'천지와 온 우주', people:['하나님','아담','하와'], image:'assets/infographics/01_creation.png', summary:'하나님이 말씀으로 천지와 만물을 창조하시고 사람을 하나님의 형상으로 지으신 사건입니다.', meaning:['하나님은 모든 것의 창조주이시며 주권자이심','인간은 하나님의 형상으로 지음받은 존귀한 존재','창조 세계는 하나님 보시기에 선한 질서로 시작됨'], core:['빛과 어둠을 나누심','하늘·바다·땅과 생명체를 창조하심','사람을 창조하시고 복을 주심','일곱째 날 안식하심'], connect:['성막','십자가','새창조']},
'adam-eve':{title:'아담과 하와', era:'창조와 원역사', period:'창조 직후', scripture:'창세기 2장', place:'에덴동산', people:['하나님','아담','하와'], image:'assets/infographics/02_adam_eve.png', summary:'하나님이 아담과 하와를 창조하시고 사람과 가정의 시작을 세우신 사건입니다.', meaning:['인간 생명과 관계의 기원을 보여줌','가정과 동역의 질서가 시작됨','하나님과 사람의 친밀한 관계가 드러남'], core:['아담을 흙으로 지으심','하와를 돕는 배필로 지으심','에덴동산을 맡기심','선악과 명령을 주심'], connect:['창조','타락','그리스도와 교회']},
'eden-exile':{title:'에덴동산 추방', era:'창조와 원역사', period:'타락 이후', scripture:'창세기 3장', place:'에덴동산', people:['하나님','아담','하와','뱀'], image:'assets/infographics/03_eden_exile.png', summary:'아담과 하와가 하나님의 명령을 어겨 죄가 들어오고 에덴동산에서 추방된 사건입니다.', meaning:['죄는 하나님과 인간의 관계를 깨뜨림','심판 중에도 구원의 약속이 주어짐','여자의 후손 약속은 복음의 첫 실마리'], core:['뱀의 유혹','선악과를 먹음','죄와 두려움의 시작','가죽옷과 여자의 후손 약속','에덴동산에서 추방'], connect:['가죽옷','여자의 후손','십자가']},
'cain-abel':{title:'가인과 아벨', era:'창조와 원역사', period:'타락 이후 초기', scripture:'창세기 4장', place:'에덴 동쪽', people:['가인','아벨','하나님'], image:'assets/infographics/04_cain_abel.png', summary:'가인이 동생 아벨을 죽이며 죄가 인간관계 안으로 확산된 사건입니다.', meaning:['예배와 마음의 태도가 중요함','분노와 질투는 죄로 이어질 수 있음','하나님은 억울한 피의 소리를 들으심'], core:['두 형제의 제사','가인의 분노','아벨 살해','가인에 대한 심판과 표'], connect:['제사','피','십자가']},
'noah-ark':{title:'노아의 방주', era:'창조와 원역사', period:'홍수 시대', scripture:'창세기 6~9장', place:'온 땅, 방주, 아라랏', people:['하나님','노아','노아의 가족'], image:'assets/infographics/05_noah_ark.png', summary:'죄악이 가득한 세상을 홍수로 심판하시되 노아와 가족을 방주로 구원하신 사건입니다.', meaning:['하나님은 죄를 심판하심','심판 중에도 구원의 길을 예비하심','언약의 신실하심이 무지개로 나타남'], core:['방주 건축 명령','홍수 심판','방주의 구원','아라랏에 머묾','무지개 언약'], connect:['심판','구원','세례']},
'babel-tower':{title:'바벨탑', era:'창조와 원역사', period:'홍수 이후', scripture:'창세기 11장', place:'시날 평지', people:['시날 사람들','하나님'], image:'assets/infographics/06_babel_tower.png', summary:'사람들이 자기 이름을 내려고 탑을 쌓자 하나님이 언어를 혼잡하게 하여 흩으신 사건입니다.', meaning:['하나님 없는 인간 중심 문명의 한계를 보여줌','교만은 흩어짐과 혼란을 낳음','오순절 성령강림의 회복 흐름과 연결됨'], core:['시날에 모임','탑 건축 계획','언어 혼잡','온 땅으로 흩어짐'], connect:['아브라함','오순절','열방 복음']},
'abraham-call':{title:'아브라함의 부르심', era:'족장 시대', period:'BC 2000경', scripture:'창세기 12장', place:'갈대아 우르, 하란, 가나안', people:['하나님','아브라함','사라'], image:'assets/infographics/07_abraham_call.png', summary:'하나님이 아브라함을 부르시고 땅과 후손과 복의 언약을 주신 사건입니다.', meaning:['구속사의 언약 흐름이 본격적으로 시작됨','믿음과 순종의 길을 보여줌','한 사람을 통해 열방을 복 주시는 계획이 드러남'], core:['본토 친척 아비 집을 떠나라','가나안으로 이동','큰 민족과 복의 약속','믿음의 여정 시작'], connect:['언약','이스라엘','그리스도']},
'lot-sodom':{title:'롯과 소돔', era:'족장 시대', period:'아브라함 시대', scripture:'창세기 18~19장', place:'소돔과 고모라', people:['롯','아브라함','천사들'], image:'assets/infographics/08_lot_sodom.png', summary:'소돔과 고모라가 죄악으로 심판받고 롯의 가족이 구출된 사건입니다.', meaning:['죄악에 대한 하나님의 심판을 보여줌','의인을 기억하시는 하나님의 긍휼이 드러남','세상 선택의 위험성을 경고함'], core:['소돔의 죄악','아브라함의 중보','롯의 구출','소돔과 고모라 심판'], connect:['중보','심판','구원']},
'jacob-ladder':{title:'야곱의 사닥다리', era:'족장 시대', period:'야곱 시대', scripture:'창세기 28장', place:'벧엘', people:['하나님','야곱'], image:'assets/infographics/09_jacob_ladder.png', summary:'도망 중이던 야곱이 벧엘에서 하늘 사닥다리 환상을 보고 언약의 약속을 받은 사건입니다.', meaning:['하나님은 실패한 사람도 언약 안에서 붙드심','하늘과 땅을 잇는 은혜의 통로가 드러남','벧엘은 하나님 임재의 장소로 기억됨'], core:['야곱의 도피','사닥다리 환상','언약 재확인','벧엘로 이름 지음'], connect:['벧엘','임재','그리스도']},
'jabbok-wrestling':{title:'야곱의 얍복강 씨름', era:'족장 시대', period:'야곱 시대', scripture:'창세기 32장', place:'얍복강', people:['하나님','야곱'], image:'assets/infographics/10_jabbok_wrestling.png', summary:'야곱이 얍복강에서 하나님과 씨름하고 이스라엘이라는 새 이름을 받은 사건입니다.', meaning:['야곱의 인생이 속임에서 의존으로 바뀜','이스라엘이라는 언약 공동체 이름이 시작됨','하나님 앞에서 깨어지는 변화가 나타남'], core:['에서와의 만남을 앞둔 두려움','밤새 씨름','환도뼈를 침','이스라엘 이름을 받음'], connect:['이스라엘','회개','새 이름']},
'joseph-dream':{title:'요셉의 꿈', era:'족장 시대', period:'요셉 청년기', scripture:'창세기 37장', place:'가나안', people:['요셉','야곱','형들'], image:'assets/infographics/11_joseph_dream.png', summary:'요셉이 꿈을 꾸고 형들의 미움을 받아 애굽으로 팔려 가는 사건입니다.', meaning:['하나님의 섭리는 고난 속에서도 진행됨','인간의 악도 하나님의 계획 안에서 사용될 수 있음','요셉 이야기는 구원의 큰 흐름을 준비함'], core:['요셉의 꿈','형들의 시기','구덩이에 던져짐','애굽으로 팔림'], connect:['섭리','고난','구원']},
'joseph-governor':{title:'요셉의 애굽 총리 등극', era:'족장 시대', period:'BC 1800경', scripture:'창세기 41~50장', place:'애굽', people:['요셉','바로','야곱의 가족'], image:'assets/infographics/12_joseph_governor.png', summary:'요셉이 애굽의 총리가 되어 흉년 속에서 가족과 많은 사람을 살린 사건입니다.', meaning:['하나님의 섭리가 고난을 구원의 도구로 바꾸심','용서와 화해의 메시지가 드러남','이스라엘이 애굽에 머무는 배경이 마련됨'], core:['바로의 꿈 해석','총리 등극','흉년 대비','형제들과 재회','야곱 가족의 애굽 이주'], connect:['용서','구원','출애굽의 배경']},
'moses-birth':{title:'모세의 탄생', era:'출애굽과 광야 시대', period:'출애굽 이전', scripture:'출애굽기 1~2장', place:'애굽, 나일강', people:['모세','요게벳','바로의 딸'], image:'assets/infographics/13_moses_birth.png', summary:'히브리 남자아이를 죽이라는 명령 속에서 모세가 태어나 보존된 사건입니다.', meaning:['하나님은 위기 속에서도 구원의 사람을 준비하심','작은 갈대상자가 큰 구원 역사의 시작이 됨','인간 권력보다 하나님의 섭리가 앞섬'], core:['남자아이 학살 명령','모세의 출생','갈대상자에 담김','바로의 딸에게 발견됨','왕궁에서 자람'], connect:['요셉 이후 애굽','출애굽','구원자 예표']},
'burning-bush':{title:'떨기나무 소명', era:'출애굽과 광야 시대', period:'모세 80세 무렵', scripture:'출애굽기 3~4장', place:'호렙산', people:['하나님','모세'], image:'assets/infographics/14_burning_bush.png', summary:'하나님이 불타는 떨기나무 가운데 모세를 부르시고 이스라엘 해방 사명을 맡기신 사건입니다.', meaning:['하나님은 자기 백성의 고통을 들으심','부르심은 능력보다 순종을 요구함','여호와의 이름이 계시됨'], core:['떨기나무가 타지만 사라지지 않음','거룩한 땅 선언','모세를 보내심','나는 스스로 있는 자 계시'], connect:['모세의 탄생','출애굽 사명','시내산']},
'ten-plagues':{title:'애굽의 10가지 재앙', era:'출애굽과 광야 시대', period:'출애굽 직전', scripture:'출애굽기 7~12장', place:'애굽', people:['하나님','모세','아론','바로'], image:'assets/infographics/15_ten_plagues.png', summary:'하나님이 애굽에 열 가지 재앙을 내리시며 바로의 완고함을 꺾고 이스라엘을 구원하신 사건입니다.', meaning:['여호와가 참 하나님이심을 드러냄','우상과 제국 권력의 무력함을 폭로함','구원은 하나님의 강한 손으로 이루어짐'], core:['피','개구리','이','파리','가축 죽음','악성 종기','우박','메뚜기','흑암','장자의 죽음'], connect:['유월절','출애굽','심판과 구원']},
'passover':{title:'유월절', era:'출애굽과 광야 시대', period:'출애굽 밤', scripture:'출애굽기 12장', place:'애굽 고센', people:['하나님','모세','이스라엘 백성'], image:'assets/infographics/16_passover.png', summary:'어린양의 피를 문설주에 바른 집은 심판이 넘어가고 이스라엘이 해방된 사건입니다.', meaning:['피를 통한 구원의 핵심 예표','하나님의 심판과 구원이 동시에 나타남','그리스도의 십자가와 성찬으로 연결됨'], core:['어린양을 잡음','피를 문설주에 바름','무교병과 쓴 나물','장자 재앙이 넘어감','출애굽 시작'], connect:['어린양','십자가','성찬']},
'red-sea':{title:'홍해의 기적', era:'출애굽과 광야 시대', period:'출애굽 직후', scripture:'출애굽기 14~15장', place:'홍해', people:['하나님','모세','이스라엘','바로의 군대'], image:'assets/infographics/17_red_sea.png', summary:'하나님이 홍해를 가르셔서 이스라엘을 건너게 하시고 애굽 군대를 심판하신 사건입니다.', meaning:['구원은 막힌 길을 여시는 하나님의 능력으로 이루어짐','애굽의 추격이 완전히 끊어짐','세례와 새 출발의 이미지로 연결됨'], core:['애굽 군대의 추격','백성의 두려움','홍해가 갈라짐','이스라엘이 마른 땅으로 건넘','애굽 군대가 수장됨'], connect:['출애굽','세례','구원의 노래']},
'manna-quail':{title:'만나와 메추라기', era:'출애굽과 광야 시대', period:'광야 여정', scripture:'출애굽기 16장', place:'신 광야', people:['하나님','모세','이스라엘'], image:'assets/infographics/18_manna_quail.png', summary:'광야에서 먹을 것이 없다고 원망하는 백성에게 하나님이 만나와 메추라기를 공급하신 사건입니다.', meaning:['하나님은 광야에서도 일용할 양식을 주심','믿음은 매일의 순종으로 훈련됨','만나는 생명의 떡이신 그리스도와 연결됨'], core:['백성의 원망','하늘에서 만나가 내림','저녁에 메추라기 공급','하루치만 거두는 훈련','안식일 규례'], connect:['광야 훈련','생명의 떡','일용할 양식']},
'sinai-commandments':{title:'시내산 십계명', era:'출애굽과 광야 시대', period:'출애굽 후 시내산', scripture:'출애굽기 19~20장', place:'시내산', people:['하나님','모세','이스라엘'], image:'assets/infographics/19_sinai_commandments.png', summary:'하나님이 시내산에서 이스라엘과 언약을 맺고 십계명을 주신 사건입니다.', meaning:['해방된 백성은 언약 백성으로 살아야 함','율법은 구원받은 백성의 삶의 기준임','하나님 사랑과 이웃 사랑의 틀이 제시됨'], core:['시내산 도착','언약 체결','십계명 수여','백성의 두려움','거룩한 백성의 삶 요구'], connect:['언약','율법','산상수훈']},
'golden-calf':{title:'금송아지 사건', era:'출애굽과 광야 시대', period:'시내산 체류 중', scripture:'출애굽기 32장', place:'시내산 아래', people:['아론','모세','이스라엘'], image:'assets/infographics/20_golden_calf.png', summary:'모세가 산에 오른 사이 백성이 금송아지를 만들어 예배하며 언약을 깨뜨린 사건입니다.', meaning:['구원받은 백성도 우상숭배의 유혹에 빠질 수 있음','중보의 필요성이 드러남','하나님의 거룩과 긍휼이 함께 나타남'], core:['모세의 지연','금송아지 제작','우상 숭배','모세의 중보','심판과 회복'], connect:['우상숭배','중보자','언약 갱신']},
'tabernacle':{title:'성막 건축', era:'출애굽과 광야 시대', period:'시내산 이후', scripture:'출애굽기 25~40장', place:'광야 진영', people:['하나님','모세','브살렐','오홀리압'], image:'assets/infographics/21_tabernacle.png', summary:'하나님이 명령하신 양식대로 성막을 세워 이스라엘 가운데 임재하신 사건입니다.', meaning:['하나님은 자기 백성 가운데 거하시는 분','예배와 속죄의 중심이 마련됨','성막은 그리스도의 임재와 구속을 예표함'], core:['성막 설계 명령','예물 드림','기구 제작','성막 완성','여호와의 영광이 충만함'], connect:['임재','제사','성전','그리스도']},
'wilderness-40':{title:'광야 40년', era:'출애굽과 광야 시대', period:'BC 1446~1406경', scripture:'민수기, 신명기', place:'시내 광야, 가데스바네아, 모압 평지', people:['모세','아론','여호수아','갈렙','이스라엘'], image:'assets/infographics/22_wilderness_40.png', summary:'불신앙과 원망으로 출애굽 1세대가 광야에서 훈련받고 새 세대가 약속의 땅을 준비한 시기입니다.', meaning:['불신앙은 약속의 지연을 낳음','광야는 심판인 동시에 훈련의 학교임','새 세대는 말씀으로 다시 준비됨'], core:['가데스바네아 정탐','불신앙과 원망','40년 광야 생활','출애굽 1세대의 죽음','새 세대 준비'], connect:['믿음','훈련','신명기 언약 갱신']},
'bronze-serpent':{title:'놋뱀 사건', era:'출애굽과 광야 시대', period:'광야 말기', scripture:'민수기 21장', place:'광야 길', people:['하나님','모세','이스라엘'], image:'assets/infographics/23_bronze_serpent.png', summary:'원망으로 불뱀에 물린 백성이 놋뱀을 바라볼 때 살아난 사건입니다.', meaning:['심판 중에도 하나님은 구원의 길을 주심','구원은 하나님의 말씀을 믿고 바라보는 데 있음','예수님의 십자가 사건과 직접 연결됨'], core:['백성의 원망','불뱀의 심판','모세의 중보','놋뱀을 장대에 듦','바라본 자가 살아남'], connect:['민수기 21장','요한복음 3장','십자가']}
};
